In [1]:
import numpy as np

a = np.array([1, 5, 3, 4, 2])

a

array([1, 5, 3, 4, 2])

In [2]:
a.sum()

15

In [3]:
a.mean()

3.0

In [4]:
a.min()

1

In [5]:
a.max()

5

In [6]:
a.sort()

a

array([1, 2, 3, 4, 5])

In [7]:
a.shape

(5,)

In [8]:
a.tolist()

[1, 2, 3, 4, 5]

In [9]:
string = a.tostring()

string

b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00'

In [10]:
a > 3

array([False, False, False,  True,  True])

In [11]:
a < 3

array([ True,  True, False, False, False])

In [12]:
a[a > 3]

array([4, 5])

In [13]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
b.shape

(3, 3)

In [15]:
b.sum(axis=0)

array([12, 15, 18])

In [16]:
b.mean()

5.0

In [17]:
b.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [18]:
''.join([str(i) for i in b.flat])

'123456789'

In [19]:
b[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [20]:
b[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
b.shape = (1, 9)

b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [22]:
b.reshape((3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
c = np.linspace(-10, 10, 11)

c

array([-10.,  -8.,  -6.,  -4.,  -2.,   0.,   2.,   4.,   6.,   8.,  10.])

In [24]:
d = np.arange(-10, 10, 1)

d

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [25]:
np.random.shuffle(d)

d

array([  1,  -2,  -8,  -3,   0,  -4,  -6, -10,   2,   3,  -5,   8,  -1,
        -7,   9,  -9,   4,   5,   6,   7])

In [26]:
e = np.random.rand()

e

0.7691552498854416

In [27]:
f = np.random.randint(-10, 10)

f

6

In [51]:
g = np.random.random_integers(-10, 10 + 1, 5)

g

c:\users\камп\appdata\local\programs\python\python35-32\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(-10, 11 + 1) instead
  """Entry point for launching an IPython kernel.


array([  5,  -9,   1,  -5, -10])

In [29]:
x = np.linspace(-10, 10, 21)

x

array([-10.,  -9.,  -8.,  -7.,  -6.,  -5.,  -4.,  -3.,  -2.,  -1.,   0.,
         1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [30]:
x * 3

array([-30., -27., -24., -21., -18., -15., -12.,  -9.,  -6.,  -3.,   0.,
         3.,   6.,   9.,  12.,  15.,  18.,  21.,  24.,  27.,  30.])

In [31]:
x + 5

array([-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,
        8.,  9., 10., 11., 12., 13., 14., 15.])

In [32]:
np.tanh(x)

array([-1.        , -0.99999997, -0.99999977, -0.99999834, -0.99998771,
       -0.9999092 , -0.9993293 , -0.99505475, -0.96402758, -0.76159416,
        0.        ,  0.76159416,  0.96402758,  0.99505475,  0.9993293 ,
        0.9999092 ,  0.99998771,  0.99999834,  0.99999977,  0.99999997,
        1.        ])

In [33]:
x.dtype

dtype('float64')

In [34]:
x.astype(int)

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9,  10])

In [35]:
x.argmax(), x.argmin()

(20, 0)

In [37]:
np.unique(x)

array([-10.,  -9.,  -8.,  -7.,  -6.,  -5.,  -4.,  -3.,  -2.,  -1.,   0.,
         1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [41]:
x = x[:16]

x

array([-10.,  -9.,  -8.,  -7.,  -6.,  -5.,  -4.,  -3.,  -2.,  -1.,   0.,
         1.,   2.,   3.,   4.,   5.])

In [42]:
x.shape = (4, 4)

x

array([[-10.,  -9.,  -8.,  -7.],
       [ -6.,  -5.,  -4.,  -3.],
       [ -2.,  -1.,   0.,   1.],
       [  2.,   3.,   4.,   5.]])

In [43]:
x.diagonal()

array([-10.,  -5.,   0.,   5.])

In [45]:
x.dot(x)

array([[156., 122.,  88.,  54.],
       [ 92.,  74.,  56.,  38.],
       [ 28.,  26.,  24.,  22.],
       [-36., -22.,  -8.,   6.]])

In [46]:
x @ x

array([[156., 122.,  88.,  54.],
       [ 92.,  74.,  56.,  38.],
       [ 28.,  26.,  24.,  22.],
       [-36., -22.,  -8.,   6.]])