In [1]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import LabelBinarizer
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import StandardScaler

from sklearn.datasets import load_iris

<h1>Label Binarizer</h1>

In [2]:
label_bin = LabelBinarizer()

data = [1, 4, 5, 6, 2, 7, 8, 4, 5, 3, 5]

label_bin.fit(data)

label_bin.classes_

array([1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
data = [5, 6, 2 , 3]

label_bin.transform(data)

array([[0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0]])

<h1>Label Encoder</h1>

In [4]:
label_enc = LabelEncoder()

data = ['label1', 'label2', 'label3', 'label4', 'label5']

label_enc.fit_transform(data)

array([0, 1, 2, 3, 4], dtype=int64)

In [5]:
label_enc.classes_

array(['label1', 'label2', 'label3', 'label4', 'label5'], dtype='<U6')

  <h1>OneHotEncoder</h1>

In [6]:
one_hot_enc = OneHotEncoder(sparse=False)

data = np.array(['France', 'Russia', 'USA', 'USA', 'Ukraine', 'Germany']).reshape(-1, 1)

one_hot_enc.fit(data)

OneHotEncoder(categorical_features=None, categories=None, drop=None,
              dtype=<class 'numpy.float64'>, handle_unknown='error',
              n_values=None, sparse=False)

In [7]:
x = np.array(['France', 'Russia', 'USA']).reshape(-1, 1)

one_hot_enc.transform(x)

array([[1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

<h1>Standard Scaler & Normalizer</h1>

In [9]:
scaler = StandardScaler()
normalizer = Normalizer()

data = load_iris().data[:, :3]
columns = load_iris().feature_names[:3]

main_df = pd.DataFrame(data[:5], columns=columns)

std_data = scaler.fit_transform(data)

std_df = pd.DataFrame(std_data[:5], columns=columns)

norm_data = normalizer.fit_transform(data)

norm_df = pd.DataFrame(norm_data[:5], columns=columns)

print('Main data'); print(main_df) 
print('Standarded'); print(std_df) 
print('Normalized'); print(norm_df)

Main data
   sepal length (cm)  sepal width (cm)  petal length (cm)
0                5.1               3.5                1.4
1                4.9               3.0                1.4
2                4.7               3.2                1.3
3                4.6               3.1                1.5
4                5.0               3.6                1.4
Standarded
   sepal length (cm)  sepal width (cm)  petal length (cm)
0          -0.900681          1.019004          -1.340227
1          -1.143017         -0.131979          -1.340227
2          -1.385353          0.328414          -1.397064
3          -1.506521          0.098217          -1.283389
4          -1.021849          1.249201          -1.340227
Normalized
   sepal length (cm)  sepal width (cm)  petal length (cm)
0           0.804172          0.551883           0.220753
1           0.828606          0.507310           0.236745
2           0.805806          0.548634           0.222883
3           0.800515          0.539477  